const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const {createCanvas,loadImage,ImageData}=require('@napi-rs/canvas');
const root=require('node:path').resolve(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});
const win=dom.window;const canvases=new WeakMap();
function backing(c){let n=canvases.get(c);if(!n||n.width!==c.width||n.height!==c.height){n=createCanvas(Math.max(1,c.width),Math.max(1,c.height));canvases.set(c,n);}return n;}
win.HTMLCanvasElement.prototype.getContext=function(){const ctx=backing(this).getContext('2d');return new Proxy(ctx,{get(target,key){if(key==='drawImage')return(source,...args)=>target.drawImage(source instanceof win.HTMLCanvasElement?backing(source):source,...args);const value=target[key];return typeof value==='function'?value.bind(target):value;},set(target,key,value){target[key]=value;return true;}});};
win.HTMLCanvasElement.prototype.toDataURL=function(){return backing(this).toDataURL('image/png');};win.HTMLCanvasElement.prototype.setPointerCapture=()=>{};
win.HTMLElement.prototype.getBoundingClientRect=function(){return{x:0,y:0,left:0,top:0,width:800,height:600,right:800,bottom:600};};
win.matchMedia=()=>({matches:false});win.structuredClone=structuredClone;win.ImageData=ImageData;win.ResizeObserver=class{observe(){}};win.document.fonts={ready:Promise.resolve()};win.URL.createObjectURL=()=>'';win.URL.revokeObjectURL=()=>{};
win.__image=async src=>{const i=await loadImage(src);Object.defineProperty(i,'naturalWidth',{value:i.width});Object.defineProperty(i,'naturalHeight',{value:i.height});return i;};
Object.defineProperty(win.navigator,'platform',{value:'MacIntel'});win.console=console;win.TextEncoder=TextEncoder;
let code=fs.readFileSync(root+'/context-fill.js','utf8').replaceAll('export ','')+'\n'+fs.readFileSync(root+'/text-effects.js','utf8').replaceAll('export ','')+'\n'+fs.readFileSync(root+'/vendor/qrcode.js','utf8').replace('export default qrcode;','')+'\n'+fs.readFileSync(root+'/editor-geometry.js','utf8').replaceAll('export ','')+'\n'+fs.readFileSync(root+'/photo-pixels.js','utf8').replaceAll('export ','');
code+='\nconst makeCanvas=(w,h)=>{const c=document.createElement("canvas");c.width=w;c.height=h;return c;};const image=window.__image;const blob=async()=>new Blob();const segment=async c=>c,enlarge=async c=>c,fill=async c=>c,regions=async()=>[];\n';
code+=fs.readFileSync(root+'/main.js','utf8').replace(/^import .*;\n/gm,'');
code+='\nwindow.__test={get project(){return project},get working(){return working},get selection(){return editorSelection},get history(){return history},get tool(){return editTool},selected:()=>currentLayer(),get docs(){return documentRecords},get activeId(){return activeDocumentId},switchDocument,closeDocument,serializeDocument,restoreSavedDocuments,layerContent,copySelectedLayer,pasteCopiedLayer,openDesignAI,closeDesignAI,activateStudio,selectionCombine,selectedRasterAction,draw,trace,restore,modifyLayer};';
win.eval(code);
const $=id=>win.document.getElementById(id),T=win.__test;
const change=id=>$(id).onchange(new win.Event('change'));
(async()=>{
 $('document-width').value=80;$('document-height').value=60;$('new-document').click();assert.equal(T.working.width,80);assert.equal(T.working.height,60);
 // Editing text must use the current inspector values, not those restored by checkpoint/update.
 $('text').value='Avant';$('add-text').click();assert.equal(T.selected().text,'Avant');$('edit-text').value='Après';$('font').value='Georgia';$('text-color').value='#ff0000';$('text-bg-enabled').checked=true;$('text-bg').value='#0000ff';$('text-padding').value=7;$('text-size').value=22;$('update-text').click();assert.equal(T.selected().text,'Après');assert.equal(T.selected().font,'Georgia');assert.equal(T.selected().color,'#ff0000');assert.equal(T.selected().textBackground,'#0000ff');assert.equal(T.selected().padding,7);
 $('blend-mode').value='multiply';change('blend-mode');assert.equal(T.selected().blend,'multiply');
 $('layer-lock').click();const scale=T.selected().scale;$('layer-size').value=150;$('layer-size').oninput();assert.equal(T.selected().scale,scale);$('layer-lock').click();
 // Selection delete affects only selected pixels; undo restores the entire composition.
 $('layer-list').value='base';$('layer-list').onchange();T.working.getContext('2d').fillStyle='#ff0000';T.working.getContext('2d').fillRect(0,0,80,60);T.draw();T.activateStudio('select-rect');
 const e=(x,y)=>({button:0,pointerId:1,clientX:x,clientY:y,preventDefault(){},shiftKey:false,altKey:false});$('overlay').onpointerdown(e(100,100));$('overlay').onpointermove(e(400,400));$('overlay').onpointerup(e(400,400));assert.ok(T.selection);$('select-delete').click();assert.equal(T.working.getContext('2d').getImageData(20,20,1,1).data[3],0);assert.equal(T.working.getContext('2d').getImageData(70,50,1,1).data[3],255);await $('undo').onclick();assert.equal(T.working.getContext('2d').getImageData(20,20,1,1).data[3],255);
 $('select-none').click();T.activateStudio('filters');$('pixel-filter').value='invert';$('filter-apply').click();const pixel=T.working.getContext('2d').getImageData(20,20,1,1).data;assert.deepEqual(Array.from(pixel),[0,255,255,255]);
 $('qr-text').value='https://example.com/été';$('qr-add').click();assert.ok(T.selected().name.startsWith('QR'));assert.ok(T.selected().width>100);assert.equal(win.document.body.dataset.inspector,'layers');
 $('theme-toggle').click();assert.equal(win.document.documentElement.dataset.theme,'dark');
 const {validate}=require(root+'/desktop/store.cjs');validate({version:1,updatedAt:null,session:{name:'test.png',type:'image/png',source:'AAAA',result:'AAAA',project:T.project,tool:'compose'}});
 const firstId=T.activeId,firstCanvas=T.working,firstLayers=T.project.layers.length,firstHistory=T.history.length;
 $('document-width').value=40;$('document-height').value=30;$('new-document').click();const secondId=T.activeId;assert.notEqual(secondId,firstId);assert.equal(T.docs.size,2);assert.equal(T.history.length,0);assert.equal(T.working.width,40);T.switchDocument(firstId);assert.equal(T.working,firstCanvas);assert.equal(T.project.layers.length,firstLayers);assert.equal(T.history.length,firstHistory);T.switchDocument(secondId);assert.equal(T.working.width,40);T.closeDocument(secondId);assert.equal(T.docs.size,1);assert.equal(T.activeId,firstId);assert.ok(!T.docs.has(''));
 T.openDesignAI();assert.equal($('design-ai').hidden,false);assert.equal($('generate-options').parentElement.id,'ai-settings');T.closeDesignAI();assert.equal($('design-ai').hidden,true);assert.notEqual($('generate-options').parentElement.id,'ai-settings');
 const saved={...T.serializeDocument(T.docs.get(firstId)),documentId:firstId,documents:[]};validate({version:1,updatedAt:null,session:saved});
 const textLayer=T.project.layers.find(l=>l.kind==='text');$('layer-list').value=textLayer.id;$('layer-list').onchange();$('text-effect').value='stair';change('text-effect');$('text-effect-amount').value=65;change('text-effect-amount');$('text-outline-width').value=2;change('text-outline-width');$('text-shadow').checked=true;change('text-shadow');assert.equal(T.selected().textEffect,'stair');assert.equal(T.selected().effectAmount,65);assert.equal(T.selected().shadowEnabled,true);assert.ok(T.layerContent(T.selected()).height>30);
 const copyKey=new win.KeyboardEvent('keydown',{key:'c',metaKey:true,bubbles:true,cancelable:true});win.document.body.dispatchEvent(copyKey);assert.equal(copyKey.defaultPrevented,true);const oldCount=T.project.layers.length;await T.pasteCopiedLayer();assert.equal(T.project.layers.length,oldCount+1);assert.equal(T.selected().textEffect,'stair');assert.equal(T.selected().text,'Après');assert.notEqual(T.selected().id,textLayer.id);
 const immutableText=T.selected().text;$('mask-black').click();assert.ok(T.selected().maskData);const invisible=T.layerContent(T.selected());assert.ok(Array.from(invisible.getContext('2d').getImageData(0,0,invisible.width,invisible.height).data).filter((_,i)=>i%4===3).every(a=>a===0));$('mask-white').click();$('mask-gradient').click();assert.ok(T.selected().maskData);assert.equal(T.selected().text,immutableText);$('mask-enable').click();assert.equal(T.selected().maskDisabled,true);$('mask-enable').click();assert.equal(T.selected().maskDisabled,false);
 $('mask-black').click();$('mask-paint-mode').value='show';$('mask-hardness').value=100;$('mask-paint').click();$('overlay').onpointerdown(e(600,500));$('overlay').onpointerup(e(600,500));let mi=await loadImage(T.selected().maskData),mc=createCanvas(mi.width,mi.height);mc.getContext('2d').drawImage(mi,0,0);assert.equal(mc.getContext('2d').getImageData(Math.floor(mi.width/2),Math.floor(mi.height/2),1,1).data[3],255);assert.equal(T.selected().text,immutableText);$('mask-paint-mode').value='hide';$('overlay').onpointerdown(e(600,500));$('overlay').onpointerup(e(600,500));mi=await loadImage(T.selected().maskData);mc=createCanvas(mi.width,mi.height);mc.getContext('2d').drawImage(mi,0,0);assert.equal(mc.getContext('2d').getImageData(Math.floor(mi.width/2),Math.floor(mi.height/2),1,1).data[3],0);
 validate({version:1,updatedAt:null,session:{name:'effects.png',type:'image/png',source:'AAAA',result:'AAAA',project:T.project,tool:'compose'}});
 console.log('PASS: text editing, text background, blend persistence, locked layer, selection deletion, atomic undo, pixel filter, dark theme, project validation');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
