import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {pipeline} from 'node:stream/promises';import {Readable} from 'node:stream';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),hash=b=>createHash('sha256').update(b).digest('hex');
await fs.mkdir('desktop-runtime',{recursive:true});
for(const name of ['onnxruntime-node','onnxruntime-common']){const entry=name==='onnxruntime-node'?require.resolve(name):createRequire(require.resolve('onnxruntime-node')).resolve(name);let base=path.dirname(entry);while(!await fs.readFile(path.join(base,'package.json'),'utf8').then(s=>JSON.parse(s).name===name,()=>false))base=path.dirname(base);await fs.cp(base,path.join('desktop-runtime',name),{recursive:true,dereference:true});}
await fs.rm('desktop-runtime/onnxruntime-node/bin/napi-v6/linux',{recursive:true,force:true});await fs.mkdir('desktop-models',{recursive:true});
const manifest=JSON.parse(await fs.readFile(new URL('./models.json',import.meta.url)));
for(const m of manifest){const file='desktop-models/'+m.id+'.onnx';if(await fs.readFile(file).then(b=>hash(b)===m.sha256,()=>false))continue;const r=await fetch(m.url);if(!r.ok)throw Error('Download failed '+m.id);await pipeline(Readable.fromWeb(r.body),(await import('node:fs')).createWriteStream(file+'.tmp'));if(hash(await fs.readFile(file+'.tmp'))!==m.sha256)throw Error('Model checksum failed '+m.id);await fs.rename(file+'.tmp',file);console.log(m.id+' ready');}
// Node is intentionally separate from Electron: ORT allocations must not use Chromium's allocator.
const version='24.9.0';const checks={'darwin-arm64':['tar.gz','961024296c2a8e60daed0784f8b61e0fab5c51d197502a92eff052c72b53209b'],'darwin-x64':['tar.gz','6c9ac12d3160538d96d456dc59a8fec1479e3f8b20bfc0d61bc809eb9ec11417'],'win-x64':['zip','6873514c3e6a012917cc6f95ce48a6289253370d025f1b69db290d70feebfa6e']};
await fs.mkdir('node-runtime',{recursive:true});
for(const [target,[extension,sha]] of Object.entries(checks)){const folder='node-runtime/'+target.replace('darwin','mac');const executable=folder+(target.startsWith('win')?'/node.exe':'/node');if(await fs.stat(executable).then(()=>true,()=>false))continue;const file=`node-v${version}-${target}.${extension}`,r=await fetch('https://nodejs.org/dist/v'+version+'/'+file);if(!r.ok)throw Error('Node download failed');const bytes=Buffer.from(await r.arrayBuffer());if(hash(bytes)!==sha)throw Error('Node checksum failed');await fs.writeFile('node-runtime/'+file,bytes);await fs.mkdir(folder,{recursive:true});if(target.startsWith('win')){execFileSync('unzip',['-j','-o','node-runtime/'+file,`node-v${version}-${target}/node.exe`,`node-v${version}-${target}/LICENSE`,'-d',folder]);}else{execFileSync('tar',['-xzf','node-runtime/'+file,'-C','node-runtime',`node-v${version}-${target}/bin/node`,`node-v${version}-${target}/LICENSE`]);await fs.rename(`node-runtime/node-v${version}-${target}/bin/node`,executable);await fs.rename(`node-runtime/node-v${version}-${target}/LICENSE`,folder+'/LICENSE');await fs.rm(`node-runtime/node-v${version}-${target}`,{recursive:true,force:true});}await fs.rm('node-runtime/'+file);}
console.log('Local models, standalone Node and ONNX Runtime ready. Run download-model.mjs for IS-Net resources too.');
