const fs=require('node:fs/promises');const path=require('node:path');const {createHash}=require('node:crypto');const catalog=require('./generation-catalog.json');
function validateGeneration(request){const r={model:'sdxs',width:512,height:512,steps:1,cfg:1,negative:'',...request},spec=catalog.find(m=>m.id===r.model);if(!spec||typeof r.prompt!=='string'||!r.prompt.trim()||r.prompt.length>2000||typeof r.negative!=='string'||r.negative.length>1500||!Number.isInteger(r.seed)||r.seed<0||r.seed>2147483647||![r.width,r.height].every(v=>Number.isInteger(v)&&v>=256&&v<=spec.maxSide&&v%64===0)||!Number.isInteger(r.steps)||r.steps<1||r.steps>spec.maxSteps||!Number.isFinite(r.cfg)||r.cfg<1||r.cfg>12)throw Error('Paramètres de génération invalides.');if(spec.maxSteps===1&&(r.steps!==1||r.cfg!==1))throw Error('SDXS utilise une étape et CFG 1.');return{request:r,spec};}
class GenerationModels{
 constructor(directory,bundled,fetcher=fetch){this.directory=directory;this.bundled=bundled;this.fetcher=fetcher;this.controller=null;this.progress={active:false,received:0,total:0};}
 file(spec){return path.join(spec.id==='sdxs'?this.bundled:this.directory,spec.file);}
 async list(){return Promise.all(catalog.map(async spec=>{let installed=false;try{installed=(await fs.stat(this.file(spec))).size===spec.bytes;}catch{}const {url,sha256,...publicSpec}=spec;return{...publicSpec,installed};}));}
 cancel(){this.controller?.abort();}
 async install(id){const spec=catalog.find(m=>m.id===id);if(!spec||!spec.url)throw Error('Modèle inconnu ou déjà embarqué.');if(this.controller)throw Error('Un téléchargement est déjà en cours.');this.controller=new AbortController();const signal=this.controller.signal,target=this.file(spec),temp=target+'.download';let handle;this.progress={active:true,received:0,total:spec.bytes};try{await fs.mkdir(this.directory,{recursive:true});const space=await fs.statfs(this.directory);if(space.bavail*space.bsize<spec.bytes+256*1024*1024)throw Error('Espace disque insuffisant pour ce modèle.');const response=await this.fetcher(spec.url,{signal});if(!response.ok)throw Error('Téléchargement impossible : HTTP '+response.status);handle=await fs.open(temp,'w',0o600);const hash=createHash('sha256');for await(const chunk of response.body){if(signal.aborted)throw Error('Téléchargement annulé.');const bytes=Buffer.from(chunk);this.progress.received+=bytes.length;if(this.progress.received>spec.bytes)throw Error('Taille du modèle invalide.');hash.update(bytes);await handle.writeFile(bytes);}if(signal.aborted)throw Error('Téléchargement annulé.');if(this.progress.received!==spec.bytes||hash.digest('hex')!==spec.sha256)throw Error('La vérification SHA-256 du modèle a échoué.');await handle.sync();await handle.close();handle=null;await fs.rename(temp,target);await fs.writeFile(target+'.source.json',JSON.stringify({name:spec.name,source:spec.source,license:spec.license,sha256:spec.sha256},null,2));return{installed:true};}catch(e){throw Error(signal.aborted?'Téléchargement annulé.':e.message);}finally{await handle?.close();await fs.rm(temp,{force:true});this.controller=null;this.progress.active=false;}}
}
module.exports={GenerationModels,validateGeneration,catalog};
